### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by lbmn** [blmvxer/nim-nmap#2]
One of Nim's top advocacy points is the degree to which it and its module ecosystem is [copyfree](http://copyfree.org/standard/) - anyone can use it for whatever purpose without becoming subjected to pages and pages of legal threats that no one *really* understands...

Nim uses the [MIT license](https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html) for all of its compiler, stdlib, and tooling - and that is also what nimble recommends as the default for new modules.

What are your reasons for using the extremely restrictive and violent GPLv3 license?  A lot of people (including myself) will boycott your software if you do.

**Comment by blmvxer** [comment]
Consider it fixed

**Comment by lbmn** [comment]
Thank you very much.  :smiley:

**Comment by blmvxer** [comment]
Anytime man. Now let's try to get this API off the ground ;)
